sonar.projectKey=tetloose-next
sonar.projectName=Tetloose Next
sonar.sources=app,src
sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/coverage/**,**/storybook-static/**

# Disable readonly props rule globally
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S6759
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.tsx
